/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Branch {
  #[serde(rename = "_links")]
  _links: Option<::models::BranchLinks>,
  #[serde(rename = "commit")]
  commit: Option<::models::BranchCommit>,
  #[serde(rename = "name")]
  name: Option<String>
}

impl Branch {
  pub fn new() -> Branch {
    Branch {
      _links: None,
      commit: None,
      name: None
    }
  }

  pub fn set__links(&mut self, _links: ::models::BranchLinks) {
    self._links = Some(_links);
  }

  pub fn with__links(mut self, _links: ::models::BranchLinks) -> Branch {
    self._links = Some(_links);
    self
  }

  pub fn _links(&self) -> Option<&::models::BranchLinks> {
    self._links.as_ref()
  }

  pub fn reset__links(&mut self) {
    self._links = None;
  }

  pub fn set_commit(&mut self, commit: ::models::BranchCommit) {
    self.commit = Some(commit);
  }

  pub fn with_commit(mut self, commit: ::models::BranchCommit) -> Branch {
    self.commit = Some(commit);
    self
  }

  pub fn commit(&self) -> Option<&::models::BranchCommit> {
    self.commit.as_ref()
  }

  pub fn reset_commit(&mut self) {
    self.commit = None;
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> Branch {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

}



