/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BranchLinks {
  #[serde(rename = "html")]
  html: Option<String>,
  #[serde(rename = "self")]
  _self: Option<String>
}

impl BranchLinks {
  pub fn new() -> BranchLinks {
    BranchLinks {
      html: None,
      _self: None
    }
  }

  pub fn set_html(&mut self, html: String) {
    self.html = Some(html);
  }

  pub fn with_html(mut self, html: String) -> BranchLinks {
    self.html = Some(html);
    self
  }

  pub fn html(&self) -> Option<&String> {
    self.html.as_ref()
  }

  pub fn reset_html(&mut self) {
    self.html = None;
  }

  pub fn set__self(&mut self, _self: String) {
    self._self = Some(_self);
  }

  pub fn with__self(mut self, _self: String) -> BranchLinks {
    self._self = Some(_self);
    self
  }

  pub fn _self(&self) -> Option<&String> {
    self._self.as_ref()
  }

  pub fn reset__self(&mut self) {
    self._self = None;
  }

}



