/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Commit {
  #[serde(rename = "author")]
  author: Option<::models::BranchCommitAuthor>,
  #[serde(rename = "commit")]
  commit: Option<::models::BranchCommitCommit>,
  #[serde(rename = "committer")]
  committer: Option<::models::BranchCommitAuthor>,
  #[serde(rename = "files")]
  files: Option<Vec<::models::CommitFiles>>,
  #[serde(rename = "parents")]
  parents: Option<Vec<::models::BranchCommitCommitTree>>,
  #[serde(rename = "sha")]
  sha: Option<String>,
  #[serde(rename = "stats")]
  stats: Option<::models::CommitStats>,
  #[serde(rename = "url")]
  url: Option<String>
}

impl Commit {
  pub fn new() -> Commit {
    Commit {
      author: None,
      commit: None,
      committer: None,
      files: None,
      parents: None,
      sha: None,
      stats: None,
      url: None
    }
  }

  pub fn set_author(&mut self, author: ::models::BranchCommitAuthor) {
    self.author = Some(author);
  }

  pub fn with_author(mut self, author: ::models::BranchCommitAuthor) -> Commit {
    self.author = Some(author);
    self
  }

  pub fn author(&self) -> Option<&::models::BranchCommitAuthor> {
    self.author.as_ref()
  }

  pub fn reset_author(&mut self) {
    self.author = None;
  }

  pub fn set_commit(&mut self, commit: ::models::BranchCommitCommit) {
    self.commit = Some(commit);
  }

  pub fn with_commit(mut self, commit: ::models::BranchCommitCommit) -> Commit {
    self.commit = Some(commit);
    self
  }

  pub fn commit(&self) -> Option<&::models::BranchCommitCommit> {
    self.commit.as_ref()
  }

  pub fn reset_commit(&mut self) {
    self.commit = None;
  }

  pub fn set_committer(&mut self, committer: ::models::BranchCommitAuthor) {
    self.committer = Some(committer);
  }

  pub fn with_committer(mut self, committer: ::models::BranchCommitAuthor) -> Commit {
    self.committer = Some(committer);
    self
  }

  pub fn committer(&self) -> Option<&::models::BranchCommitAuthor> {
    self.committer.as_ref()
  }

  pub fn reset_committer(&mut self) {
    self.committer = None;
  }

  pub fn set_files(&mut self, files: Vec<::models::CommitFiles>) {
    self.files = Some(files);
  }

  pub fn with_files(mut self, files: Vec<::models::CommitFiles>) -> Commit {
    self.files = Some(files);
    self
  }

  pub fn files(&self) -> Option<&Vec<::models::CommitFiles>> {
    self.files.as_ref()
  }

  pub fn reset_files(&mut self) {
    self.files = None;
  }

  pub fn set_parents(&mut self, parents: Vec<::models::BranchCommitCommitTree>) {
    self.parents = Some(parents);
  }

  pub fn with_parents(mut self, parents: Vec<::models::BranchCommitCommitTree>) -> Commit {
    self.parents = Some(parents);
    self
  }

  pub fn parents(&self) -> Option<&Vec<::models::BranchCommitCommitTree>> {
    self.parents.as_ref()
  }

  pub fn reset_parents(&mut self) {
    self.parents = None;
  }

  pub fn set_sha(&mut self, sha: String) {
    self.sha = Some(sha);
  }

  pub fn with_sha(mut self, sha: String) -> Commit {
    self.sha = Some(sha);
    self
  }

  pub fn sha(&self) -> Option<&String> {
    self.sha.as_ref()
  }

  pub fn reset_sha(&mut self) {
    self.sha = None;
  }

  pub fn set_stats(&mut self, stats: ::models::CommitStats) {
    self.stats = Some(stats);
  }

  pub fn with_stats(mut self, stats: ::models::CommitStats) -> Commit {
    self.stats = Some(stats);
    self
  }

  pub fn stats(&self) -> Option<&::models::CommitStats> {
    self.stats.as_ref()
  }

  pub fn reset_stats(&mut self) {
    self.stats = None;
  }

  pub fn set_url(&mut self, url: String) {
    self.url = Some(url);
  }

  pub fn with_url(mut self, url: String) -> Commit {
    self.url = Some(url);
    self
  }

  pub fn url(&self) -> Option<&String> {
    self.url.as_ref()
  }

  pub fn reset_url(&mut self) {
    self.url = None;
  }

}



