/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CommentBody {
  #[serde(rename = "body")]
  body: String
}

impl CommentBody {
  pub fn new(body: String) -> CommentBody {
    CommentBody {
      body: body
    }
  }

  pub fn set_body(&mut self, body: String) {
    self.body = body;
  }

  pub fn with_body(mut self, body: String) -> CommentBody {
    self.body = body;
    self
  }

  pub fn body(&self) -> &String {
    &self.body
  }


}



