/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateFile {
  #[serde(rename = "commit")]
  commit: Option<::models::CreateFileCommit>,
  #[serde(rename = "content")]
  content: Option<::models::CreateFileContent>
}

impl CreateFile {
  pub fn new() -> CreateFile {
    CreateFile {
      commit: None,
      content: None
    }
  }

  pub fn set_commit(&mut self, commit: ::models::CreateFileCommit) {
    self.commit = Some(commit);
  }

  pub fn with_commit(mut self, commit: ::models::CreateFileCommit) -> CreateFile {
    self.commit = Some(commit);
    self
  }

  pub fn commit(&self) -> Option<&::models::CreateFileCommit> {
    self.commit.as_ref()
  }

  pub fn reset_commit(&mut self) {
    self.commit = None;
  }

  pub fn set_content(&mut self, content: ::models::CreateFileContent) {
    self.content = Some(content);
  }

  pub fn with_content(mut self, content: ::models::CreateFileContent) -> CreateFile {
    self.content = Some(content);
    self
  }

  pub fn content(&self) -> Option<&::models::CreateFileContent> {
    self.content.as_ref()
  }

  pub fn reset_content(&mut self) {
    self.content = None;
  }

}



