/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeleteFileBody {
  #[serde(rename = "committer")]
  committer: Option<::models::CreateFileBodyCommitter>,
  #[serde(rename = "message")]
  message: Option<String>,
  #[serde(rename = "sha")]
  sha: Option<String>
}

impl DeleteFileBody {
  pub fn new() -> DeleteFileBody {
    DeleteFileBody {
      committer: None,
      message: None,
      sha: None
    }
  }

  pub fn set_committer(&mut self, committer: ::models::CreateFileBodyCommitter) {
    self.committer = Some(committer);
  }

  pub fn with_committer(mut self, committer: ::models::CreateFileBodyCommitter) -> DeleteFileBody {
    self.committer = Some(committer);
    self
  }

  pub fn committer(&self) -> Option<&::models::CreateFileBodyCommitter> {
    self.committer.as_ref()
  }

  pub fn reset_committer(&mut self) {
    self.committer = None;
  }

  pub fn set_message(&mut self, message: String) {
    self.message = Some(message);
  }

  pub fn with_message(mut self, message: String) -> DeleteFileBody {
    self.message = Some(message);
    self
  }

  pub fn message(&self) -> Option<&String> {
    self.message.as_ref()
  }

  pub fn reset_message(&mut self) {
    self.message = None;
  }

  pub fn set_sha(&mut self, sha: String) {
    self.sha = Some(sha);
  }

  pub fn with_sha(mut self, sha: String) -> DeleteFileBody {
    self.sha = Some(sha);
    self
  }

  pub fn sha(&self) -> Option<&String> {
    self.sha.as_ref()
  }

  pub fn reset_sha(&mut self) {
    self.sha = None;
  }

}



