/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IssuesCommentsInnerLinksHtml {
  #[serde(rename = "href")]
  href: Option<String>
}

impl IssuesCommentsInnerLinksHtml {
  pub fn new() -> IssuesCommentsInnerLinksHtml {
    IssuesCommentsInnerLinksHtml {
      href: None
    }
  }

  pub fn set_href(&mut self, href: String) {
    self.href = Some(href);
  }

  pub fn with_href(mut self, href: String) -> IssuesCommentsInnerLinksHtml {
    self.href = Some(href);
    self
  }

  pub fn href(&self) -> Option<&String> {
    self.href.as_ref()
  }

  pub fn reset_href(&mut self) {
    self.href = None;
  }

}



