/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct MergePullBody {
  #[serde(rename = "commit_message")]
  commit_message: Option<String>
}

impl MergePullBody {
  pub fn new() -> MergePullBody {
    MergePullBody {
      commit_message: None
    }
  }

  pub fn set_commit_message(&mut self, commit_message: String) {
    self.commit_message = Some(commit_message);
  }

  pub fn with_commit_message(mut self, commit_message: String) -> MergePullBody {
    self.commit_message = Some(commit_message);
    self
  }

  pub fn commit_message(&self) -> Option<&String> {
    self.commit_message.as_ref()
  }

  pub fn reset_commit_message(&mut self) {
    self.commit_message = None;
  }

}



