mod asset;
pub use self::asset::Asset;
mod asset_patch;
pub use self::asset_patch::AssetPatch;
mod asset_uploader;
pub use self::asset_uploader::AssetUploader;
mod assets;
pub use self::assets::Assets;
mod assets_inner;
pub use self::assets_inner::AssetsInner;
mod assignees;
pub use self::assignees::Assignees;
mod assignees_inner;
pub use self::assignees_inner::AssigneesInner;
mod blob;
pub use self::blob::Blob;
mod blobs;
pub use self::blobs::Blobs;
mod branch;
pub use self::branch::Branch;
mod branch_commit;
pub use self::branch_commit::BranchCommit;
mod branch_commit_author;
pub use self::branch_commit_author::BranchCommitAuthor;
mod branch_commit_commit;
pub use self::branch_commit_commit::BranchCommitCommit;
mod branch_commit_commit_author;
pub use self::branch_commit_commit_author::BranchCommitCommitAuthor;
mod branch_commit_commit_tree;
pub use self::branch_commit_commit_tree::BranchCommitCommitTree;
mod branch__links;
pub use self::branch__links::BranchLinks;
mod branches;
pub use self::branches::Branches;
mod branches_inner;
pub use self::branches_inner::BranchesInner;
mod code_frequency_stats;
pub use self::code_frequency_stats::CodeFrequencyStats;
mod collaborators;
pub use self::collaborators::Collaborators;
mod comment;
pub use self::comment::Comment;
mod comment_body;
pub use self::comment_body::CommentBody;
mod comments;
pub use self::comments::Comments;
mod comments_inner;
pub use self::comments_inner::CommentsInner;
mod commit;
pub use self::commit::Commit;
mod commit_activity_stats;
pub use self::commit_activity_stats::CommitActivityStats;
mod commit_activity_stats_inner;
pub use self::commit_activity_stats_inner::CommitActivityStatsInner;
mod commit_body;
pub use self::commit_body::CommitBody;
mod commit_comments;
pub use self::commit_comments::CommitComments;
mod commit_files;
pub use self::commit_files::CommitFiles;
mod commit_stats;
pub use self::commit_stats::CommitStats;
mod commits;
pub use self::commits::Commits;
mod compare_commits;
pub use self::compare_commits::CompareCommits;
mod comparecommits_base_commit;
pub use self::comparecommits_base_commit::ComparecommitsBaseCommit;
mod comparecommits_base_commit_author;
pub use self::comparecommits_base_commit_author::ComparecommitsBaseCommitAuthor;
mod comparecommits_base_commit_commit;
pub use self::comparecommits_base_commit_commit::ComparecommitsBaseCommitCommit;
mod comparecommits_base_commit_commit_author;
pub use self::comparecommits_base_commit_commit_author::ComparecommitsBaseCommitCommitAuthor;
mod comparecommits_files;
pub use self::comparecommits_files::ComparecommitsFiles;
mod contents_path;
pub use self::contents_path::ContentsPath;
mod contentspath__links;
pub use self::contentspath__links::ContentspathLinks;
mod contributors;
pub use self::contributors::Contributors;
mod contributors_inner;
pub use self::contributors_inner::ContributorsInner;
mod contributors_stats;
pub use self::contributors_stats::ContributorsStats;
mod contributors_stats_inner;
pub use self::contributors_stats_inner::ContributorsStatsInner;
mod contributors_stats_inner_weeks;
pub use self::contributors_stats_inner_weeks::ContributorsStatsInnerWeeks;
mod create_download;
pub use self::create_download::CreateDownload;
mod create_file;
pub use self::create_file::CreateFile;
mod create_file_body;
pub use self::create_file_body::CreateFileBody;
mod create_file_body_committer;
pub use self::create_file_body_committer::CreateFileBodyCommitter;
mod create_file_commit;
pub use self::create_file_commit::CreateFileCommit;
mod create_file_commit_parents;
pub use self::create_file_commit_parents::CreateFileCommitParents;
mod create_file_content;
pub use self::create_file_content::CreateFileContent;
mod delete_file;
pub use self::delete_file::DeleteFile;
mod delete_file_body;
pub use self::delete_file_body::DeleteFileBody;
mod delete_file_commit;
pub use self::delete_file_commit::DeleteFileCommit;
mod deployment;
pub use self::deployment::Deployment;
mod deployment_payload;
pub use self::deployment_payload::DeploymentPayload;
mod deployment_resp;
pub use self::deployment_resp::DeploymentResp;
mod deployment_statuses;
pub use self::deployment_statuses::DeploymentStatuses;
mod deployment_statuses_create;
pub use self::deployment_statuses_create::DeploymentStatusesCreate;
mod deploymentstatuses_inner;
pub use self::deploymentstatuses_inner::DeploymentstatusesInner;
mod download_body;
pub use self::download_body::DownloadBody;
mod downloads;
pub use self::downloads::Downloads;
mod edit_team;
pub use self::edit_team::EditTeam;
mod emails_post;
pub use self::emails_post::EmailsPost;
mod emojis;
pub use self::emojis::Emojis;
mod event;
pub use self::event::Event;
mod event_issue;
pub use self::event_issue::EventIssue;
mod event_issue_labels;
pub use self::event_issue_labels::EventIssueLabels;
mod event_issue_milestone;
pub use self::event_issue_milestone::EventIssueMilestone;
mod event_issue_pull_request;
pub use self::event_issue_pull_request::EventIssuePullRequest;
mod events;
pub use self::events::Events;
mod events_repo;
pub use self::events_repo::EventsRepo;
mod feeds;
pub use self::feeds::Feeds;
mod feeds__links;
pub use self::feeds__links::FeedsLinks;
mod feeds__links_current_user;
pub use self::feeds__links_current_user::FeedsLinksCurrentUser;
mod fork;
pub use self::fork::Fork;
mod fork_body;
pub use self::fork_body::ForkBody;
mod forks;
pub use self::forks::Forks;
mod forks_inner;
pub use self::forks_inner::ForksInner;
mod gist;
pub use self::gist::Gist;
mod gist_files;
pub use self::gist_files::GistFiles;
mod gist_files_ring_erl;
pub use self::gist_files_ring_erl::GistFilesRingErl;
mod gist_forks;
pub use self::gist_forks::GistForks;
mod gist_history;
pub use self::gist_history::GistHistory;
mod gists;
pub use self::gists::Gists;
mod gists_inner;
pub use self::gists_inner::GistsInner;
mod git_commit;
pub use self::git_commit::GitCommit;
mod git_ref_patch;
pub use self::git_ref_patch::GitRefPatch;
mod gitignore;
pub use self::gitignore::Gitignore;
mod gitignore_lang;
pub use self::gitignore_lang::GitignoreLang;
mod head_branch;
pub use self::head_branch::HeadBranch;
mod head_branch_body;
pub use self::head_branch_body::HeadBranchBody;
mod head_branch_object;
pub use self::head_branch_object::HeadBranchObject;
mod heads;
pub use self::heads::Heads;
mod heads_inner;
pub use self::heads_inner::HeadsInner;
mod hook;
pub use self::hook::Hook;
mod hook_body;
pub use self::hook_body::HookBody;
mod hook_inner;
pub use self::hook_inner::HookInner;
mod hook_inner_config;
pub use self::hook_inner_config::HookInnerConfig;
mod issue;
pub use self::issue::Issue;
mod issue_body;
pub use self::issue_body::IssueBody;
mod issues;
pub use self::issues::Issues;
mod issues_comment;
pub use self::issues_comment::IssuesComment;
mod issues_comments;
pub use self::issues_comments::IssuesComments;
mod issues_comments_inner;
pub use self::issues_comments_inner::IssuesCommentsInner;
mod issues_comments_inner__links;
pub use self::issues_comments_inner__links::IssuesCommentsInnerLinks;
mod issues_comments_inner__links_html;
pub use self::issues_comments_inner__links_html::IssuesCommentsInnerLinksHtml;
mod key;
pub use self::key::Key;
mod key_body;
pub use self::key_body::KeyBody;
mod keys;
pub use self::keys::Keys;
mod keys_inner;
pub use self::keys_inner::KeysInner;
mod label;
pub use self::label::Label;
mod labels;
pub use self::labels::Labels;
mod labels_body;
pub use self::labels_body::LabelsBody;
mod labels_inner;
pub use self::labels_inner::LabelsInner;
mod languages;
pub use self::languages::Languages;
mod markdown;
pub use self::markdown::Markdown;
mod members;
pub use self::members::Members;
mod merge;
pub use self::merge::Merge;
mod merge_pull_body;
pub use self::merge_pull_body::MergePullBody;
mod merges_body;
pub use self::merges_body::MergesBody;
mod merges_conflict;
pub use self::merges_conflict::MergesConflict;
mod merges_successful;
pub use self::merges_successful::MergesSuccessful;
mod merges_successful_author;
pub use self::merges_successful_author::MergesSuccessfulAuthor;
mod merges_successful_commit;
pub use self::merges_successful_commit::MergesSuccessfulCommit;
mod meta;
pub use self::meta::Meta;
mod milestone;
pub use self::milestone::Milestone;
mod milestone_body;
pub use self::milestone_body::MilestoneBody;
mod milestone_update;
pub use self::milestone_update::MilestoneUpdate;
mod model_ref;
pub use self::model_ref::ModelRef;
mod notification_mark_read;
pub use self::notification_mark_read::NotificationMarkRead;
mod notifications;
pub use self::notifications::Notifications;
mod notifications_repository;
pub use self::notifications_repository::NotificationsRepository;
mod notifications_subject;
pub use self::notifications_subject::NotificationsSubject;
mod org_members;
pub use self::org_members::OrgMembers;
mod org_public_members;
pub use self::org_public_members::OrgPublicMembers;
mod org_teams;
pub use self::org_teams::OrgTeams;
mod org_teams_post;
pub use self::org_teams_post::OrgTeamsPost;
mod organization;
pub use self::organization::Organization;
mod organization_as_team_member;
pub use self::organization_as_team_member::OrganizationAsTeamMember;
mod organization_as_team_member_errors;
pub use self::organization_as_team_member_errors::OrganizationAsTeamMemberErrors;
mod participation_stats;
pub use self::participation_stats::ParticipationStats;
mod patch_gist;
pub use self::patch_gist::PatchGist;
mod patch_gist_files;
pub use self::patch_gist_files::PatchGistFiles;
mod patch_gist_files_file1_txt;
pub use self::patch_gist_files_file1_txt::PatchGistFilesFile1Txt;
mod patch_gist_files_old_name_txt;
pub use self::patch_gist_files_old_name_txt::PatchGistFilesOldNameTxt;
mod patch_org;
pub use self::patch_org::PatchOrg;
mod post_comment;
pub use self::post_comment::PostComment;
mod post_gist;
pub use self::post_gist::PostGist;
mod post_gist_files;
pub use self::post_gist_files::PostGistFiles;
mod post_repo;
pub use self::post_repo::PostRepo;
mod pull_request;
pub use self::pull_request::PullRequest;
mod pull_request_base;
pub use self::pull_request_base::PullRequestBase;
mod pull_request_base_repo;
pub use self::pull_request_base_repo::PullRequestBaseRepo;
mod pull_request__links;
pub use self::pull_request__links::PullRequestLinks;
mod pull_update;
pub use self::pull_update::PullUpdate;
mod pulls;
pub use self::pulls::Pulls;
mod pulls_comment;
pub use self::pulls_comment::PullsComment;
mod pulls_comment_post;
pub use self::pulls_comment_post::PullsCommentPost;
mod pulls_comments;
pub use self::pulls_comments::PullsComments;
mod pulls_inner;
pub use self::pulls_inner::PullsInner;
mod pulls_inner_base;
pub use self::pulls_inner_base::PullsInnerBase;
mod pulls_post;
pub use self::pulls_post::PullsPost;
mod punch_card_stats;
pub use self::punch_card_stats::PunchCardStats;
mod put_subscription;
pub use self::put_subscription::PutSubscription;
mod rate_limit;
pub use self::rate_limit::RateLimit;
mod rate_limit_rate;
pub use self::rate_limit_rate::RateLimitRate;
mod readme;
pub use self::readme::Readme;
mod ref_body;
pub use self::ref_body::RefBody;
mod ref_inner;
pub use self::ref_inner::RefInner;
mod ref_status;
pub use self::ref_status::RefStatus;
mod ref_status_inner;
pub use self::ref_status_inner::RefStatusInner;
mod ref_status_inner_statuses;
pub use self::ref_status_inner_statuses::RefStatusInnerStatuses;
mod refs;
pub use self::refs::Refs;
mod refs_body;
pub use self::refs_body::RefsBody;
mod refs_inner;
pub use self::refs_inner::RefsInner;
mod release;
pub use self::release::Release;
mod release_assets;
pub use self::release_assets::ReleaseAssets;
mod release_create;
pub use self::release_create::ReleaseCreate;
mod releases;
pub use self::releases::Releases;
mod releases_inner;
pub use self::releases_inner::ReleasesInner;
mod repo;
pub use self::repo::Repo;
mod repo_comments;
pub use self::repo_comments::RepoComments;
mod repo_comments_inner;
pub use self::repo_comments_inner::RepoCommentsInner;
mod repo_commit;
pub use self::repo_commit::RepoCommit;
mod repo_commit_body;
pub use self::repo_commit_body::RepoCommitBody;
mod repo_deployments;
pub use self::repo_deployments::RepoDeployments;
mod repo_edit;
pub use self::repo_edit::RepoEdit;
mod repo_organization;
pub use self::repo_organization::RepoOrganization;
mod repo_parent;
pub use self::repo_parent::RepoParent;
mod repo_source;
pub use self::repo_source::RepoSource;
mod repodeployments_inner;
pub use self::repodeployments_inner::RepodeploymentsInner;
mod repos;
pub use self::repos::Repos;
mod repositories;
pub use self::repositories::Repositories;
mod search_code;
pub use self::search_code::SearchCode;
mod search_issues;
pub use self::search_issues::SearchIssues;
mod search_issues_by_keyword;
pub use self::search_issues_by_keyword::SearchIssuesByKeyword;
mod search_repositories;
pub use self::search_repositories::SearchRepositories;
mod search_repositories_by_keyword;
pub use self::search_repositories_by_keyword::SearchRepositoriesByKeyword;
mod search_user_by_email;
pub use self::search_user_by_email::SearchUserByEmail;
mod search_users;
pub use self::search_users::SearchUsers;
mod search_users_by_keyword;
pub use self::search_users_by_keyword::SearchUsersByKeyword;
mod searchcode_items;
pub use self::searchcode_items::SearchcodeItems;
mod searchcode_repository;
pub use self::searchcode_repository::SearchcodeRepository;
mod searchissues_items;
pub use self::searchissues_items::SearchissuesItems;
mod searchissuesbykeyword_issues;
pub use self::searchissuesbykeyword_issues::SearchissuesbykeywordIssues;
mod searchrepositories_items;
pub use self::searchrepositories_items::SearchrepositoriesItems;
mod searchrepositories_owner;
pub use self::searchrepositories_owner::SearchrepositoriesOwner;
mod searchrepositoriesbykeyword_repositories;
pub use self::searchrepositoriesbykeyword_repositories::SearchrepositoriesbykeywordRepositories;
mod searchuserbyemail_user;
pub use self::searchuserbyemail_user::SearchuserbyemailUser;
mod searchusers_items;
pub use self::searchusers_items::SearchusersItems;
mod searchusersbykeyword_users;
pub use self::searchusersbykeyword_users::SearchusersbykeywordUsers;
mod stargazers;
pub use self::stargazers::Stargazers;
mod subscribition;
pub use self::subscribition::Subscribition;
mod subscribition_body;
pub use self::subscribition_body::SubscribitionBody;
mod subscription;
pub use self::subscription::Subscription;
mod tag;
pub use self::tag::Tag;
mod tags;
pub use self::tags::Tags;
mod tags_tagger;
pub use self::tags_tagger::TagsTagger;
mod team;
pub use self::team::Team;
mod team_membership;
pub use self::team_membership::TeamMembership;
mod team_repos;
pub use self::team_repos::TeamRepos;
mod teams;
pub use self::teams::Teams;
mod teams_list;
pub use self::teams_list::TeamsList;
mod teamslist_inner;
pub use self::teamslist_inner::TeamslistInner;
mod teamslist_inner_organization;
pub use self::teamslist_inner_organization::TeamslistInnerOrganization;
mod tree;
pub use self::tree::Tree;
mod tree_tree;
pub use self::tree_tree::TreeTree;
mod trees;
pub use self::trees::Trees;
mod trees_tree;
pub use self::trees_tree::TreesTree;
mod user;
pub use self::user::User;
mod user_emails;
pub use self::user_emails::UserEmails;
mod user_emails_final;
pub use self::user_emails_final::UserEmailsFinal;
mod user_keys;
pub use self::user_keys::UserKeys;
mod user_keys_key_id;
pub use self::user_keys_key_id::UserKeysKeyId;
mod user_keys_post;
pub use self::user_keys_post::UserKeysPost;
mod user_plan;
pub use self::user_plan::UserPlan;
mod user_update;
pub use self::user_update::UserUpdate;
mod user_user_id;
pub use self::user_user_id::UserUserId;
mod user_user_id_starred;
pub use self::user_user_id_starred::UserUserIdStarred;
mod user_user_id_subscribitions;
pub use self::user_user_id_subscribitions::UserUserIdSubscribitions;
mod users;
pub use self::users::Users;
mod users_user_id_keys;
pub use self::users_user_id_keys::UsersUserIdKeys;
mod users_user_id_orgs;
pub use self::users_user_id_orgs::UsersUserIdOrgs;
mod useruser_idsubscribitions_inner;
pub use self::useruser_idsubscribitions_inner::UseruserIdsubscribitionsInner;

// TODO(farcaller): sort out files
pub struct File;

#[derive(Debug, Default, Deserialize, Serialize)]
pub struct ErrorUnknown;
