/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Notifications {
  #[serde(rename = "id")]
  id: Option<i32>,
  #[serde(rename = "last_read_at")]
  last_read_at: Option<String>,
  #[serde(rename = "reason")]
  reason: Option<String>,
  #[serde(rename = "repository")]
  repository: Option<::models::NotificationsRepository>,
  #[serde(rename = "subject")]
  subject: Option<::models::NotificationsSubject>,
  #[serde(rename = "unread")]
  unread: Option<bool>,
  #[serde(rename = "updated_at")]
  updated_at: Option<String>,
  #[serde(rename = "url")]
  url: Option<String>
}

impl Notifications {
  pub fn new() -> Notifications {
    Notifications {
      id: None,
      last_read_at: None,
      reason: None,
      repository: None,
      subject: None,
      unread: None,
      updated_at: None,
      url: None
    }
  }

  pub fn set_id(&mut self, id: i32) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: i32) -> Notifications {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&i32> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_last_read_at(&mut self, last_read_at: String) {
    self.last_read_at = Some(last_read_at);
  }

  pub fn with_last_read_at(mut self, last_read_at: String) -> Notifications {
    self.last_read_at = Some(last_read_at);
    self
  }

  pub fn last_read_at(&self) -> Option<&String> {
    self.last_read_at.as_ref()
  }

  pub fn reset_last_read_at(&mut self) {
    self.last_read_at = None;
  }

  pub fn set_reason(&mut self, reason: String) {
    self.reason = Some(reason);
  }

  pub fn with_reason(mut self, reason: String) -> Notifications {
    self.reason = Some(reason);
    self
  }

  pub fn reason(&self) -> Option<&String> {
    self.reason.as_ref()
  }

  pub fn reset_reason(&mut self) {
    self.reason = None;
  }

  pub fn set_repository(&mut self, repository: ::models::NotificationsRepository) {
    self.repository = Some(repository);
  }

  pub fn with_repository(mut self, repository: ::models::NotificationsRepository) -> Notifications {
    self.repository = Some(repository);
    self
  }

  pub fn repository(&self) -> Option<&::models::NotificationsRepository> {
    self.repository.as_ref()
  }

  pub fn reset_repository(&mut self) {
    self.repository = None;
  }

  pub fn set_subject(&mut self, subject: ::models::NotificationsSubject) {
    self.subject = Some(subject);
  }

  pub fn with_subject(mut self, subject: ::models::NotificationsSubject) -> Notifications {
    self.subject = Some(subject);
    self
  }

  pub fn subject(&self) -> Option<&::models::NotificationsSubject> {
    self.subject.as_ref()
  }

  pub fn reset_subject(&mut self) {
    self.subject = None;
  }

  pub fn set_unread(&mut self, unread: bool) {
    self.unread = Some(unread);
  }

  pub fn with_unread(mut self, unread: bool) -> Notifications {
    self.unread = Some(unread);
    self
  }

  pub fn unread(&self) -> Option<&bool> {
    self.unread.as_ref()
  }

  pub fn reset_unread(&mut self) {
    self.unread = None;
  }

  pub fn set_updated_at(&mut self, updated_at: String) {
    self.updated_at = Some(updated_at);
  }

  pub fn with_updated_at(mut self, updated_at: String) -> Notifications {
    self.updated_at = Some(updated_at);
    self
  }

  pub fn updated_at(&self) -> Option<&String> {
    self.updated_at.as_ref()
  }

  pub fn reset_updated_at(&mut self) {
    self.updated_at = None;
  }

  pub fn set_url(&mut self, url: String) {
    self.url = Some(url);
  }

  pub fn with_url(mut self, url: String) -> Notifications {
    self.url = Some(url);
    self
  }

  pub fn url(&self) -> Option<&String> {
    self.url.as_ref()
  }

  pub fn reset_url(&mut self) {
    self.url = None;
  }

}



