/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NotificationMarkRead {
  #[serde(rename = "last_read_at")]
  last_read_at: Option<String>
}

impl NotificationMarkRead {
  pub fn new() -> NotificationMarkRead {
    NotificationMarkRead {
      last_read_at: None
    }
  }

  pub fn set_last_read_at(&mut self, last_read_at: String) {
    self.last_read_at = Some(last_read_at);
  }

  pub fn with_last_read_at(mut self, last_read_at: String) -> NotificationMarkRead {
    self.last_read_at = Some(last_read_at);
    self
  }

  pub fn last_read_at(&self) -> Option<&String> {
    self.last_read_at.as_ref()
  }

  pub fn reset_last_read_at(&mut self) {
    self.last_read_at = None;
  }

}



