/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PatchGist {
  #[serde(rename = "description")]
  description: Option<String>,
  #[serde(rename = "files")]
  files: Option<::models::PatchGistFiles>
}

impl PatchGist {
  pub fn new() -> PatchGist {
    PatchGist {
      description: None,
      files: None
    }
  }

  pub fn set_description(&mut self, description: String) {
    self.description = Some(description);
  }

  pub fn with_description(mut self, description: String) -> PatchGist {
    self.description = Some(description);
    self
  }

  pub fn description(&self) -> Option<&String> {
    self.description.as_ref()
  }

  pub fn reset_description(&mut self) {
    self.description = None;
  }

  pub fn set_files(&mut self, files: ::models::PatchGistFiles) {
    self.files = Some(files);
  }

  pub fn with_files(mut self, files: ::models::PatchGistFiles) -> PatchGist {
    self.files = Some(files);
    self
  }

  pub fn files(&self) -> Option<&::models::PatchGistFiles> {
    self.files.as_ref()
  }

  pub fn reset_files(&mut self) {
    self.files = None;
  }

}



