/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PostGistFiles {
  #[serde(rename = "file1.txt")]
  file1_txt: Option<::models::PatchGistFilesFile1Txt>
}

impl PostGistFiles {
  pub fn new() -> PostGistFiles {
    PostGistFiles {
      file1_txt: None
    }
  }

  pub fn set_file1_txt(&mut self, file1_txt: ::models::PatchGistFilesFile1Txt) {
    self.file1_txt = Some(file1_txt);
  }

  pub fn with_file1_txt(mut self, file1_txt: ::models::PatchGistFilesFile1Txt) -> PostGistFiles {
    self.file1_txt = Some(file1_txt);
    self
  }

  pub fn file1_txt(&self) -> Option<&::models::PatchGistFilesFile1Txt> {
    self.file1_txt.as_ref()
  }

  pub fn reset_file1_txt(&mut self) {
    self.file1_txt = None;
  }

}



