/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RefBody {
  #[serde(rename = "object")]
  object: Option<::models::HeadBranchObject>,
  #[serde(rename = "ref")]
  _ref: Option<String>,
  #[serde(rename = "url")]
  url: Option<String>
}

impl RefBody {
  pub fn new() -> RefBody {
    RefBody {
      object: None,
      _ref: None,
      url: None
    }
  }

  pub fn set_object(&mut self, object: ::models::HeadBranchObject) {
    self.object = Some(object);
  }

  pub fn with_object(mut self, object: ::models::HeadBranchObject) -> RefBody {
    self.object = Some(object);
    self
  }

  pub fn object(&self) -> Option<&::models::HeadBranchObject> {
    self.object.as_ref()
  }

  pub fn reset_object(&mut self) {
    self.object = None;
  }

  pub fn set__ref(&mut self, _ref: String) {
    self._ref = Some(_ref);
  }

  pub fn with__ref(mut self, _ref: String) -> RefBody {
    self._ref = Some(_ref);
    self
  }

  pub fn _ref(&self) -> Option<&String> {
    self._ref.as_ref()
  }

  pub fn reset__ref(&mut self) {
    self._ref = None;
  }

  pub fn set_url(&mut self, url: String) {
    self.url = Some(url);
  }

  pub fn with_url(mut self, url: String) -> RefBody {
    self.url = Some(url);
    self
  }

  pub fn url(&self) -> Option<&String> {
    self.url.as_ref()
  }

  pub fn reset_url(&mut self) {
    self.url = None;
  }

}



