/* 
 * GitHub
 *
 * Powerful collaboration, code review, and code management for open source and private projects. 
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SearchUserByEmail {
  #[serde(rename = "user")]
  user: Option<::models::SearchuserbyemailUser>
}

impl SearchUserByEmail {
  pub fn new() -> SearchUserByEmail {
    SearchUserByEmail {
      user: None
    }
  }

  pub fn set_user(&mut self, user: ::models::SearchuserbyemailUser) {
    self.user = Some(user);
  }

  pub fn with_user(mut self, user: ::models::SearchuserbyemailUser) -> SearchUserByEmail {
    self.user = Some(user);
    self
  }

  pub fn user(&self) -> Option<&::models::SearchuserbyemailUser> {
    self.user.as_ref()
  }

  pub fn reset_user(&mut self) {
    self.user = None;
  }

}



